### ISSUE TITLE
pytorch not propertly installed in clearlinux image

### ISSUE THREAD

**Issue by VictorRodriguez** [unrahul/stacker#5]
**Describe the bug**
when trying to build the image generated from stacker/stacker/dockerfiles/clearlinux/pytorch/Dockerfile

FROM clearlinux:latest

RUN swupd bundle-add openssh-server openssh-client wget curl python3-basic

RUN pip install pytorch==1.0.2

RUN pip install horovod==0.16.0

**To Reproduce**

**Expected behavior**
build the image

**Screenshots**
docker build -f stacker/stacker/dockerfiles/clearlinux/pytorch/Dockerfile .
 37           tag: torch_mkl
Sending build context to Docker daemon  263.2MB
Step 1/4 : FROM clearlinux:latest
 ---> de8efee37e76
Step 2/4 : RUN swupd bundle-add openssh-server openssh-client wget curl python3-basic
 ---> Using cache
 ---> 35d480317fe4
Step 3/4 : RUN pip install pytorch==1.0.2
 ---> Running in 8f5ac1672e1a
Collecting pytorch==1.0.2
  Downloading https://files.pythonhosted.org/packages/ee/67/f403d4ae6e9cd74b546ee88cccdb29b8415a9c1b3d80aebeb20c9ea91d96/pytorch-1.0.2.tar.gz
Installing collected packages: pytorch
    Running setup.py install for pytorch: started
    Running setup.py install for pytorch: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-857m527f/pytorch/setup.py'"'"'; __file__='"'"'/tmp/pip-install-857m527f/pytorch/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-5pn6e6od/install-record.txt --single-version-externally-managed --compile
         cwd: /tmp/pip-install-857m527f/pytorch/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-857m527f/pytorch/setup.py", line 11, in <module>
        raise Exception(message)
    Exception: You tried to install "pytorch". The package named for PyTorch is "torch"
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-857m527f/pytorch/setup.py'"'"'; __file__='"'"'/tmp/pip-install-857m527f/pytorch/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-5pn6e6od/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by unrahul** [comment]
the package name is torch, fix added to the dockerfile slices
